### ISSUE TITLE
Airi Desktop is not functioning as it should on other devices (e.g. Intel-based devices)

### ISSUE THREAD

**Issue by Purrcival** [moeru-ai/airi#146]
### Describe the bug

The settings window is not loading properly, and is showing just an empty white background, preventing me from changing settings, and the window won't close when clicked, forcing me to terminate Airi via System Informer. I cannot also drag Airi as it's stuck where it is at and is the topmost which on a small screen (in this case my 1366x768 screen, see below for display details). Hovering at the bug button also is preventing me from clicking it because of the message box showing right at the button. Please fix this. I am using an intel based laptop with an intel GPU and CPU.

What it looks like:

![Image](https://github.com/user-attachments/assets/3946ccf6-b6c8-42de-95cb-0f024c5f7393)

### System Info

My windows version for reference

![Image](https://github.com/user-attachments/assets/2141facc-59f5-4247-9258-ddf2b0273ceb)

My display info for reference

![Image](https://github.com/user-attachments/assets/26bdac15-5207-4f12-8f58-c258a9ced4ae)

My specs (according to Window's UWP app called Settings)

![Image](https://github.com/user-attachments/assets/2698a1a7-9817-4282-a44c-8768f91f350e)

### Validations

- [x] Follow our [Code of Conduct](https://github.com/moeru-ai/airi/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guide](https://github.com/moeru-ai/airi/blob/main/CONTRIBUTING.md).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by nekomeowww** [comment]
I believe this has been fixed in #144. I guess the MCP support is part of v0.5, right? Can we somehow cherry-pick this fix for existing v0.4.* releases? @LemonNekoGH

**Comment by HoshinoLunaDev** [comment]
> I believe this has been fixed in [#144](https://github.com/moeru-ai/airi/pull/144). I guess the MCP support is part of v0.5, right? Can we somehow cherry-pick this fix for existing v0.4.* releases? [@LemonNekoGH](https://github.com/LemonNekoGH)

Well I downloaded the latest version (v0.4.23) and it does this for my device. It would help to see this fixed. After all my device is using an Intel-based CPU and GPU. Here's the following system information that was just read by my System Information tool

```
[System Summary]

Item	Value	
OS Name	Microsoft Windows 11 Home	
Version	10.0.22631 Build 22631	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
System Name	LAPTOP-Q75FD8I9	
System Manufacturer	HP	
System Model	HP Laptop 15-fd0xxx	
System Type	x64-based PC	
System SKU	AP1Y7UA#ABA	
Processor	Intel(R) N200, 1000 Mhz, 4 Core(s), 4 Logical Processor(s)	
BIOS Version/Date	AMI F.11, 6/3/2024	
SMBIOS Version	3.5	
Embedded Controller Version	62.41	
BIOS Mode	UEFI	
BaseBoard Manufacturer	HP	
BaseBoard Product	8B36	
BaseBoard Version	62.41	
Platform Role	Mobile	
Secure Boot State	On	
PCR7 Configuration	Elevation Required to View	
Windows Directory	C:\windows	
System Directory	C:\windows\system32	
Boot Device	\Device\HarddiskVolume1	
Locale	United States	
Hardware Abstraction Layer	Version = "10.0.22621.2506"	
User Name	LAPTOP-Q75FD8I9\bhowe	
Time Zone	Central Daylight Time	
Installed Physical Memory (RAM)	4.00 GB	
Total Physical Memory	3.66 GB	
Available Physical Memory	433 MB	
Total Virtual Memory	8.06 GB	
Available Virtual Memory	1.62 GB	
Page File Space	4.39 GB	
Page File	C:\pagefile.sys	
Kernel DMA Protection	On	
Virtualization-based security	Not enabled	
Windows Defender Application Control policy	Enforced	
Windows Defender Application Control user mode policy	Off	
Device Encryption Support	Elevation Required to View	
Hyper-V - VM Monitor Mode Extensions	Yes	
Hyper-V - Second Level Address Translation Extensions	Yes	
Hyper-V - Virtualization Enabled in Firmware	Yes	
Hyper-V - Data Execution Protection	Yes	

[Hardware Resources]



[Conflicts/Sharing]

Resource	Device	
Memory Address 0x80400000-0x804FFFFF	Realtek RTL8851BE WiFi 6 802.11ax PCIe Adapter #4	
Memory Address 0x80400000-0x804FFFFF	PCI Express Root Complex	
Memory Address 0x80400000-0x804FFFFF	PCI Express Root Port #7 - 54BE	
		

[DMA]

Resource	Device	Status	

[Forced Hardware]

Device	PNP Device ID	

[I/O]

Resource	Device	Status	
0x0000002E-0x0000002F	Motherboard resources	OK	
0x0000004E-0x0000004F	Motherboard resources	OK	
0x00000061-0x00000061	Motherboard resources	OK	
0x00000063-0x00000063	Motherboard resources	OK	
0x00000065-0x00000065	Motherboard resources	OK	
0x00000067-0x00000067	Motherboard resources	OK	
0x00000070-0x00000070	Motherboard resources	OK	
0x00000080-0x00000080	Motherboard resources	OK	
0x00000092-0x00000092	Motherboard resources	OK	
0x000000B2-0x000000B3	Motherboard resources	OK	
0x00000680-0x0000069F	Motherboard resources	OK	
0x0000164E-0x0000164F	Motherboard resources	OK	
0x00000062-0x00000062	Microsoft ACPI-Compliant Embedded Controller	OK	
0x00000066-0x00000066	Microsoft ACPI-Compliant Embedded Controller	OK	
0x00000060-0x00000060	Standard PS/2 Keyboard	OK	
0x00000064-0x00000064	Standard PS/2 Keyboard	OK	
0x00003F00-0x00003FFF	Realtek RTL8851BE WiFi 6 802.11ax PCIe Adapter #4	OK	
0x00000020-0x00000021	Programmable interrupt controller	OK	
0x00000024-0x00000025	Programmable interrupt controller	OK	
0x00000028-0x00000029	Programmable interrupt controller	OK	
0x0000002C-0x0000002D	Programmable interrupt controller	OK	
0x00000030-0x00000031	Programmable interrupt controller	OK	
0x00000034-0x00000035	Programmable interrupt controller	OK	
0x00000038-0x00000039	Programmable interrupt controller	OK	
0x0000003C-0x0000003D	Programmable interrupt controller	OK	
0x000000A0-0x000000A1	Programmable interrupt controller	OK	
0x000000A4-0x000000A5	Programmable interrupt controller	OK	
0x000000A8-0x000000A9	Programmable interrupt controller	OK	
0x000000AC-0x000000AD	Programmable interrupt controller	OK	
0x000000B0-0x000000B1	Programmable interrupt controller	OK	
0x000000B4-0x000000B5	Programmable interrupt controller	OK	
0x000000B8-0x000000B9	Programmable interrupt controller	OK	
0x000000BC-0x000000BD	Programmable interrupt controller	OK	
0x000004D0-0x000004D1	Programmable interrupt controller	OK	
0x00000000-0x00000CF7	PCI Express Root Complex	OK	
0x00000D00-0x0000FFFF	PCI Express Root Complex	OK	
0x00000040-0x00000043	System timer	OK	
0x00000050-0x00000053	System timer	OK	
0x00003000-0x00003FFF	PCI Express Root Port #7 - 54BE	OK	
0x00002000-0x000020FE	Motherboard resources	OK	
0x00001854-0x00001857	Motherboard resources	OK	
0x00004000-0x0000403F	Intel(R) UHD Graphics	OK	

[IRQs]

Resource	Device	Status	
IRQ 26	Intel(R) Integrated Sensor Solution	OK	
IRQ 18	Intel Universal Flash Storage (UFS) Host Controller	OK	
IRQ 1	Standard PS/2 Keyboard	OK	
IRQ 4294967289	Realtek RTL8851BE WiFi 6 802.11ax PCIe Adapter #4	OK	
IRQ 4294967293	Intel(R) USB 3.10 eXtensible Host Controller - 1.20 (Microsoft)	OK	
IRQ 1024	I2C HID Device	OK	
IRQ 40	Intel(R) Serial IO I2C Host Controller - 54E9	OK	
IRQ 0	System timer	OK	
IRQ 55	Microsoft ACPI-Compliant System	OK	
IRQ 56	Microsoft ACPI-Compliant System	OK	
IRQ 57	Microsoft ACPI-Compliant System	OK	
IRQ 58	Microsoft ACPI-Compliant System	OK	
IRQ 59	Microsoft ACPI-Compliant System	OK	
IRQ 60	Microsoft ACPI-Compliant System	OK	
IRQ 61	Microsoft ACPI-Compliant System	OK	
IRQ 62	Microsoft ACPI-Compliant System	OK	
IRQ 63	Microsoft ACPI-Compliant System	OK	
IRQ 64	Microsoft ACPI-Compliant System	OK	
IRQ 65	Microsoft ACPI-Compliant System	OK	
IRQ 66	Microsoft ACPI-Compliant System	OK	
IRQ 67	Microsoft ACPI-Compliant System	OK	
IRQ 68	Microsoft ACPI-Compliant System	OK	
IRQ 69	Microsoft ACPI-Compliant System	OK	
IRQ 70	Microsoft ACPI-Compliant System	OK	
IRQ 71	Microsoft ACPI-Compliant System	OK	
IRQ 72	Microsoft ACPI-Compliant System	OK	
IRQ 73	Microsoft ACPI-Compliant System	OK	
IRQ 74	Microsoft ACPI-Compliant System	OK	
IRQ 75	Microsoft ACPI-Compliant System	OK	
IRQ 76	Microsoft ACPI-Compliant System	OK	
IRQ 77	Microsoft ACPI-Compliant System	OK	
IRQ 78	Microsoft ACPI-Compliant System	OK	
IRQ 79	Microsoft ACPI-Compliant System	OK	
IRQ 80	Microsoft ACPI-Compliant System	OK	
IRQ 81	Microsoft ACPI-Compliant System	OK	
IRQ 82	Microsoft ACPI-Compliant System	OK	
IRQ 83	Microsoft ACPI-Compliant System	OK	
IRQ 84	Microsoft ACPI-Compliant System	OK	
IRQ 85	Microsoft ACPI-Compliant System	OK	
IRQ 86	Microsoft ACPI-Compliant System	OK	
IRQ 87	Microsoft ACPI-Compliant System	OK	
IRQ 88	Microsoft ACPI-Compliant System	OK	
IRQ 89	Microsoft ACPI-Compliant System	OK	
IRQ 90	Microsoft ACPI-Compliant System	OK	
IRQ 91	Microsoft ACPI-Compliant System	OK	
IRQ 92	Microsoft ACPI-Compliant System	OK	
IRQ 93	Microsoft ACPI-Compliant System	OK	
IRQ 94	Microsoft ACPI-Compliant System	OK	
IRQ 95	Microsoft ACPI-Compliant System	OK	
IRQ 96	Microsoft ACPI-Compliant System	OK	
IRQ 97	Microsoft ACPI-Compliant System	OK	
IRQ 98	Microsoft ACPI-Compliant System	OK	
IRQ 99	Microsoft ACPI-Compliant System	OK	
IRQ 100	Microsoft ACPI-Compliant System	OK	
IRQ 101	Microsoft ACPI-Compliant System	OK	
IRQ 102	Microsoft ACPI-Compliant System	OK	
IRQ 103	Microsoft ACPI-Compliant System	OK	
IRQ 104	Microsoft ACPI-Compliant System	OK	
IRQ 105	Microsoft ACPI-Compliant System	OK	
IRQ 106	Microsoft ACPI-Compliant System	OK	
IRQ 107	Microsoft ACPI-Compliant System	OK	
IRQ 108	Microsoft ACPI-Compliant System	OK	
IRQ 109	Microsoft ACPI-Compliant System	OK	
IRQ 110	Microsoft ACPI-Compliant System	OK	
IRQ 111	Microsoft ACPI-Compliant System	OK	
IRQ 112	Microsoft ACPI-Compliant System	OK	
IRQ 113	Microsoft ACPI-Compliant System	OK	
IRQ 114	Microsoft ACPI-Compliant System	OK	
IRQ 115	Microsoft ACPI-Compliant System	OK	
IRQ 116	Microsoft ACPI-Compliant System	OK	
IRQ 117	Microsoft ACPI-Compliant System	OK	
IRQ 118	Microsoft ACPI-Compliant System	OK	
IRQ 119	Microsoft ACPI-Compliant System	OK	
IRQ 120	Microsoft ACPI-Compliant System	OK	
IRQ 121	Microsoft ACPI-Compliant System	OK	
IRQ 122	Microsoft ACPI-Compliant System	OK	
IRQ 123	Microsoft ACPI-Compliant System	OK	
IRQ 124	Microsoft ACPI-Compliant System	OK	
IRQ 125	Microsoft ACPI-Compliant System	OK	
IRQ 126	Microsoft ACPI-Compliant System	OK	
IRQ 127	Microsoft ACPI-Compliant System	OK	
IRQ 128	Microsoft ACPI-Compliant System	OK	
IRQ 129	Microsoft ACPI-Compliant System	OK	
IRQ 130	Microsoft ACPI-Compliant System	OK	
IRQ 131	Microsoft ACPI-Compliant System	OK	
IRQ 132	Microsoft ACPI-Compliant System	OK	
IRQ 133	Microsoft ACPI-Compliant System	OK	
IRQ 134	Microsoft ACPI-Compliant System	OK	
IRQ 135	Microsoft ACPI-Compliant System	OK	
IRQ 136	Microsoft ACPI-Compliant System	OK	
IRQ 137	Microsoft ACPI-Compliant System	OK	
IRQ 138	Microsoft ACPI-Compliant System	OK	
IRQ 139	Microsoft ACPI-Compliant System	OK	
IRQ 140	Microsoft ACPI-Compliant System	OK	
IRQ 141	Microsoft ACPI-Compliant System	OK	
IRQ 142	Microsoft ACPI-Compliant System	OK	
IRQ 143	Microsoft ACPI-Compliant System	OK	
IRQ 144	Microsoft ACPI-Compliant System	OK	
IRQ 145	Microsoft ACPI-Compliant System	OK	
IRQ 146	Microsoft ACPI-Compliant System	OK	
IRQ 147	Microsoft ACPI-Compliant System	OK	
IRQ 148	Microsoft ACPI-Compliant System	OK	
IRQ 149	Microsoft ACPI-Compliant System	OK	
IRQ 150	Microsoft ACPI-Compliant System	OK	
IRQ 151	Microsoft ACPI-Compliant System	OK	
IRQ 152	Microsoft ACPI-Compliant System	OK	
IRQ 153	Microsoft ACPI-Compliant System	OK	
IRQ 154	Microsoft ACPI-Compliant System	OK	
IRQ 155	Microsoft ACPI-Compliant System	OK	
IRQ 156	Microsoft ACPI-Compliant System	OK	
IRQ 157	Microsoft ACPI-Compliant System	OK	
IRQ 158	Microsoft ACPI-Compliant System	OK	
IRQ 159	Microsoft ACPI-Compliant System	OK	
IRQ 160	Microsoft ACPI-Compliant System	OK	
IRQ 161	Microsoft ACPI-Compliant System	OK	
IRQ 162	Microsoft ACPI-Compliant System	OK	
IRQ 163	Microsoft ACPI-Compliant System	OK	
IRQ 164	Microsoft ACPI-Compliant System	OK	
IRQ 165	Microsoft ACPI-Compliant System	OK	
IRQ 166	Microsoft ACPI-Compliant System	OK	
IRQ 167	Microsoft ACPI-Compliant System	OK	
IRQ 168	Microsoft ACPI-Compliant System	OK	
IRQ 169	Microsoft ACPI-Compliant System	OK	
IRQ 170	Microsoft ACPI-Compliant System	OK	
IRQ 171	Microsoft ACPI-Compliant System	OK	
IRQ 172	Microsoft ACPI-Compliant System	OK	
IRQ 173	Microsoft ACPI-Compliant System	OK	
IRQ 174	Microsoft ACPI-Compliant System	OK	
IRQ 175	Microsoft ACPI-Compliant System	OK	
IRQ 176	Microsoft ACPI-Compliant System	OK	
IRQ 177	Microsoft ACPI-Compliant System	OK	
IRQ 178	Microsoft ACPI-Compliant System	OK	
IRQ 179	Microsoft ACPI-Compliant System	OK	
IRQ 180	Microsoft ACPI-Compliant System	OK	
IRQ 181	Microsoft ACPI-Compliant System	OK	
IRQ 182	Microsoft ACPI-Compliant System	OK	
IRQ 183	Microsoft ACPI-Compliant System	OK	
IRQ 184	Microsoft ACPI-Compliant System	OK	
IRQ 185	Microsoft ACPI-Compliant System	OK	
IRQ 186	Microsoft ACPI-Compliant System	OK	
IRQ 187	Microsoft ACPI-Compliant System	OK	
IRQ 188	Microsoft ACPI-Compliant System	OK	
IRQ 189	Microsoft ACPI-Compliant System	OK	
IRQ 190	Microsoft ACPI-Compliant System	OK	
IRQ 191	Microsoft ACPI-Compliant System	OK	
IRQ 192	Microsoft ACPI-Compliant System	OK	
IRQ 193	Microsoft ACPI-Compliant System	OK	
IRQ 194	Microsoft ACPI-Compliant System	OK	
IRQ 195	Microsoft ACPI-Compliant System	OK	
IRQ 196	Microsoft ACPI-Compliant System	OK	
IRQ 197	Microsoft ACPI-Compliant System	OK	
IRQ 198	Microsoft ACPI-Compliant System	OK	
IRQ 199	Microsoft ACPI-Compliant System	OK	
IRQ 200	Microsoft ACPI-Compliant System	OK	
IRQ 201	Microsoft ACPI-Compliant System	OK	
IRQ 202	Microsoft ACPI-Compliant System	OK	
IRQ 203	Microsoft ACPI-Compliant System	OK	
IRQ 204	Microsoft ACPI-Compliant System	OK	
IRQ 256	Microsoft ACPI-Compliant System	OK	
IRQ 257	Microsoft ACPI-Compliant System	OK	
IRQ 258	Microsoft ACPI-Compliant System	OK	
IRQ 259	Microsoft ACPI-Compliant System	OK	
IRQ 260	Microsoft ACPI-Compliant System	OK	
IRQ 261	Microsoft ACPI-Compliant System	OK	
IRQ 262	Microsoft ACPI-Compliant System	OK	
IRQ 263	Microsoft ACPI-Compliant System	OK	
IRQ 264	Microsoft ACPI-Compliant System	OK	
IRQ 265	Microsoft ACPI-Compliant System	OK	
IRQ 266	Microsoft ACPI-Compliant System	OK	
IRQ 267	Microsoft ACPI-Compliant System	OK	
IRQ 268	Microsoft ACPI-Compliant System	OK	
IRQ 269	Microsoft ACPI-Compliant System	OK	
IRQ 270	Microsoft ACPI-Compliant System	OK	
IRQ 271	Microsoft ACPI-Compliant System	OK	
IRQ 272	Microsoft ACPI-Compliant System	OK	
IRQ 273	Microsoft ACPI-Compliant System	OK	
IRQ 274	Microsoft ACPI-Compliant System	OK	
IRQ 275	Microsoft ACPI-Compliant System	OK	
IRQ 276	Microsoft ACPI-Compliant System	OK	
IRQ 277	Microsoft ACPI-Compliant System	OK	
IRQ 278	Microsoft ACPI-Compliant System	OK	
IRQ 279	Microsoft ACPI-Compliant System	OK	
IRQ 280	Microsoft ACPI-Compliant System	OK	
IRQ 281	Microsoft ACPI-Compliant System	OK	
IRQ 282	Microsoft ACPI-Compliant System	OK	
IRQ 283	Microsoft ACPI-Compliant System	OK	
IRQ 284	Microsoft ACPI-Compliant System	OK	
IRQ 285	Microsoft ACPI-Compliant System	OK	
IRQ 286	Microsoft ACPI-Compliant System	OK	
IRQ 287	Microsoft ACPI-Compliant System	OK	
IRQ 288	Microsoft ACPI-Compliant System	OK	
IRQ 289	Microsoft ACPI-Compliant System	OK	
IRQ 290	Microsoft ACPI-Compliant System	OK	
IRQ 291	Microsoft ACPI-Compliant System	OK	
IRQ 292	Microsoft ACPI-Compliant System	OK	
IRQ 293	Microsoft ACPI-Compliant System	OK	
IRQ 294	Microsoft ACPI-Compliant System	OK	
IRQ 295	Microsoft ACPI-Compliant System	OK	
IRQ 296	Microsoft ACPI-Compliant System	OK	
IRQ 297	Microsoft ACPI-Compliant System	OK	
IRQ 298	Microsoft ACPI-Compliant System	OK	
IRQ 299	Microsoft ACPI-Compliant System	OK	
IRQ 300	Microsoft ACPI-Compliant System	OK	
IRQ 301	Microsoft ACPI-Compliant System	OK	
IRQ 302	Microsoft ACPI-Compliant System	OK	
IRQ 303	Microsoft ACPI-Compliant System	OK	
IRQ 304	Microsoft ACPI-Compliant System	OK	
IRQ 305	Microsoft ACPI-Compliant System	OK	
IRQ 306	Microsoft ACPI-Compliant System	OK	
IRQ 307	Microsoft ACPI-Compliant System	OK	
IRQ 308	Microsoft ACPI-Compliant System	OK	
IRQ 309	Microsoft ACPI-Compliant System	OK	
IRQ 310	Microsoft ACPI-Compliant System	OK	
IRQ 311	Microsoft ACPI-Compliant System	OK	
IRQ 312	Microsoft ACPI-Compliant System	OK	
IRQ 313	Microsoft ACPI-Compliant System	OK	
IRQ 314	Microsoft ACPI-Compliant System	OK	
IRQ 315	Microsoft ACPI-Compliant System	OK	
IRQ 316	Microsoft ACPI-Compliant System	OK	
IRQ 317	Microsoft ACPI-Compliant System	OK	
IRQ 318	Microsoft ACPI-Compliant System	OK	
IRQ 319	Microsoft ACPI-Compliant System	OK	
IRQ 320	Microsoft ACPI-Compliant System	OK	
IRQ 321	Microsoft ACPI-Compliant System	OK	
IRQ 322	Microsoft ACPI-Compliant System	OK	
IRQ 323	Microsoft ACPI-Compliant System	OK	
IRQ 324	Microsoft ACPI-Compliant System	OK	
IRQ 325	Microsoft ACPI-Compliant System	OK	
IRQ 326	Microsoft ACPI-Compliant System	OK	
IRQ 327	Microsoft ACPI-Compliant System	OK	
IRQ 328	Microsoft ACPI-Compliant System	OK	
IRQ 329	Microsoft ACPI-Compliant System	OK	
IRQ 330	Microsoft ACPI-Compliant System	OK	
IRQ 331	Microsoft ACPI-Compliant System	OK	
IRQ 332	Microsoft ACPI-Compliant System	OK	
IRQ 333	Microsoft ACPI-Compliant System	OK	
IRQ 334	Microsoft ACPI-Compliant System	OK	
IRQ 335	Microsoft ACPI-Compliant System	OK	
IRQ 336	Microsoft ACPI-Compliant System	OK	
IRQ 337	Microsoft ACPI-Compliant System	OK	
IRQ 338	Microsoft ACPI-Compliant System	OK	
IRQ 339	Microsoft ACPI-Compliant System	OK	
IRQ 340	Microsoft ACPI-Compliant System	OK	
IRQ 341	Microsoft ACPI-Compliant System	OK	
IRQ 342	Microsoft ACPI-Compliant System	OK	
IRQ 343	Microsoft ACPI-Compliant System	OK	
IRQ 344	Microsoft ACPI-Compliant System	OK	
IRQ 345	Microsoft ACPI-Compliant System	OK	
IRQ 346	Microsoft ACPI-Compliant System	OK	
IRQ 347	Microsoft ACPI-Compliant System	OK	
IRQ 348	Microsoft ACPI-Compliant System	OK	
IRQ 349	Microsoft ACPI-Compliant System	OK	
IRQ 350	Microsoft ACPI-Compliant System	OK	
IRQ 351	Microsoft ACPI-Compliant System	OK	
IRQ 352	Microsoft ACPI-Compliant System	OK	
IRQ 353	Microsoft ACPI-Compliant System	OK	
IRQ 354	Microsoft ACPI-Compliant System	OK	
IRQ 355	Microsoft ACPI-Compliant System	OK	
IRQ 356	Microsoft ACPI-Compliant System	OK	
IRQ 357	Microsoft ACPI-Compliant System	OK	
IRQ 358	Microsoft ACPI-Compliant System	OK	
IRQ 359	Microsoft ACPI-Compliant System	OK	
IRQ 360	Microsoft ACPI-Compliant System	OK	
IRQ 361	Microsoft ACPI-Compliant System	OK	
IRQ 362	Microsoft ACPI-Compliant System	OK	
IRQ 363	Microsoft ACPI-Compliant System	OK	
IRQ 364	Microsoft ACPI-Compliant System	OK	
IRQ 365	Microsoft ACPI-Compliant System	OK	
IRQ 366	Microsoft ACPI-Compliant System	OK	
IRQ 367	Microsoft ACPI-Compliant System	OK	
IRQ 368	Microsoft ACPI-Compliant System	OK	
IRQ 369	Microsoft ACPI-Compliant System	OK	
IRQ 370	Microsoft ACPI-Compliant System	OK	
IRQ 371	Microsoft ACPI-Compliant System	OK	
IRQ 372	Microsoft ACPI-Compliant System	OK	
IRQ 373	Microsoft ACPI-Compliant System	OK	
IRQ 374	Microsoft ACPI-Compliant System	OK	
IRQ 375	Microsoft ACPI-Compliant System	OK	
IRQ 376	Microsoft ACPI-Compliant System	OK	
IRQ 377	Microsoft ACPI-Compliant System	OK	
IRQ 378	Microsoft ACPI-Compliant System	OK	
IRQ 379	Microsoft ACPI-Compliant System	OK	
IRQ 380	Microsoft ACPI-Compliant System	OK	
IRQ 381	Microsoft ACPI-Compliant System	OK	
IRQ 382	Microsoft ACPI-Compliant System	OK	
IRQ 383	Microsoft ACPI-Compliant System	OK	
IRQ 384	Microsoft ACPI-Compliant System	OK	
IRQ 385	Microsoft ACPI-Compliant System	OK	
IRQ 386	Microsoft ACPI-Compliant System	OK	
IRQ 387	Microsoft ACPI-Compliant System	OK	
IRQ 388	Microsoft ACPI-Compliant System	OK	
IRQ 389	Microsoft ACPI-Compliant System	OK	
IRQ 390	Microsoft ACPI-Compliant System	OK	
IRQ 391	Microsoft ACPI-Compliant System	OK	
IRQ 392	Microsoft ACPI-Compliant System	OK	
IRQ 393	Microsoft ACPI-Compliant System	OK	
IRQ 394	Microsoft ACPI-Compliant System	OK	
IRQ 395	Microsoft ACPI-Compliant System	OK	
IRQ 396	Microsoft ACPI-Compliant System	OK	
IRQ 397	Microsoft ACPI-Compliant System	OK	
IRQ 398	Microsoft ACPI-Compliant System	OK	
IRQ 399	Microsoft ACPI-Compliant System	OK	
IRQ 400	Microsoft ACPI-Compliant System	OK	
IRQ 401	Microsoft ACPI-Compliant System	OK	
IRQ 402	Microsoft ACPI-Compliant System	OK	
IRQ 403	Microsoft ACPI-Compliant System	OK	
IRQ 404	Microsoft ACPI-Compliant System	OK	
IRQ 405	Microsoft ACPI-Compliant System	OK	
IRQ 406	Microsoft ACPI-Compliant System	OK	
IRQ 407	Microsoft ACPI-Compliant System	OK	
IRQ 408	Microsoft ACPI-Compliant System	OK	
IRQ 409	Microsoft ACPI-Compliant System	OK	
IRQ 410	Microsoft ACPI-Compliant System	OK	
IRQ 411	Microsoft ACPI-Compliant System	OK	
IRQ 412	Microsoft ACPI-Compliant System	OK	
IRQ 413	Microsoft ACPI-Compliant System	OK	
IRQ 414	Microsoft ACPI-Compliant System	OK	
IRQ 415	Microsoft ACPI-Compliant System	OK	
IRQ 416	Microsoft ACPI-Compliant System	OK	
IRQ 417	Microsoft ACPI-Compliant System	OK	
IRQ 418	Microsoft ACPI-Compliant System	OK	
IRQ 419	Microsoft ACPI-Compliant System	OK	
IRQ 420	Microsoft ACPI-Compliant System	OK	
IRQ 421	Microsoft ACPI-Compliant System	OK	
IRQ 422	Microsoft ACPI-Compliant System	OK	
IRQ 423	Microsoft ACPI-Compliant System	OK	
IRQ 424	Microsoft ACPI-Compliant System	OK	
IRQ 425	Microsoft ACPI-Compliant System	OK	
IRQ 426	Microsoft ACPI-Compliant System	OK	
IRQ 427	Microsoft ACPI-Compliant System	OK	
IRQ 428	Microsoft ACPI-Compliant System	OK	
IRQ 429	Microsoft ACPI-Compliant System	OK	
IRQ 430	Microsoft ACPI-Compliant System	OK	
IRQ 431	Microsoft ACPI-Compliant System	OK	
IRQ 432	Microsoft ACPI-Compliant System	OK	
IRQ 433	Microsoft ACPI-Compliant System	OK	
IRQ 434	Microsoft ACPI-Compliant System	OK	
IRQ 435	Microsoft ACPI-Compliant System	OK	
IRQ 436	Microsoft ACPI-Compliant System	OK	
IRQ 437	Microsoft ACPI-Compliant System	OK	
IRQ 438	Microsoft ACPI-Compliant System	OK	
IRQ 439	Microsoft ACPI-Compliant System	OK	
IRQ 440	Microsoft ACPI-Compliant System	OK	
IRQ 441	Microsoft ACPI-Compliant System	OK	
IRQ 442	Microsoft ACPI-Compliant System	OK	
IRQ 443	Microsoft ACPI-Compliant System	OK	
IRQ 444	Microsoft ACPI-Compliant System	OK	
IRQ 445	Microsoft ACPI-Compliant System	OK	
IRQ 446	Microsoft ACPI-Compliant System	OK	
IRQ 447	Microsoft ACPI-Compliant System	OK	
IRQ 448	Microsoft ACPI-Compliant System	OK	
IRQ 449	Microsoft ACPI-Compliant System	OK	
IRQ 450	Microsoft ACPI-Compliant System	OK	
IRQ 451	Microsoft ACPI-Compliant System	OK	
IRQ 452	Microsoft ACPI-Compliant System	OK	
IRQ 453	Microsoft ACPI-Compliant System	OK	
IRQ 454	Microsoft ACPI-Compliant System	OK	
IRQ 455	Microsoft ACPI-Compliant System	OK	
IRQ 456	Microsoft ACPI-Compliant System	OK	
IRQ 457	Microsoft ACPI-Compliant System	OK	
IRQ 458	Microsoft ACPI-Compliant System	OK	
IRQ 459	Microsoft ACPI-Compliant System	OK	
IRQ 460	Microsoft ACPI-Compliant System	OK	
IRQ 461	Microsoft ACPI-Compliant System	OK	
IRQ 462	Microsoft ACPI-Compliant System	OK	
IRQ 463	Microsoft ACPI-Compliant System	OK	
IRQ 464	Microsoft ACPI-Compliant System	OK	
IRQ 465	Microsoft ACPI-Compliant System	OK	
IRQ 466	Microsoft ACPI-Compliant System	OK	
IRQ 467	Microsoft ACPI-Compliant System	OK	
IRQ 468	Microsoft ACPI-Compliant System	OK	
IRQ 469	Microsoft ACPI-Compliant System	OK	
IRQ 470	Microsoft ACPI-Compliant System	OK	
IRQ 471	Microsoft ACPI-Compliant System	OK	
IRQ 472	Microsoft ACPI-Compliant System	OK	
IRQ 473	Microsoft ACPI-Compliant System	OK	
IRQ 474	Microsoft ACPI-Compliant System	OK	
IRQ 475	Microsoft ACPI-Compliant System	OK	
IRQ 476	Microsoft ACPI-Compliant System	OK	
IRQ 477	Microsoft ACPI-Compliant System	OK	
IRQ 478	Microsoft ACPI-Compliant System	OK	
IRQ 479	Microsoft ACPI-Compliant System	OK	
IRQ 480	Microsoft ACPI-Compliant System	OK	
IRQ 481	Microsoft ACPI-Compliant System	OK	
IRQ 482	Microsoft ACPI-Compliant System	OK	
IRQ 483	Microsoft ACPI-Compliant System	OK	
IRQ 484	Microsoft ACPI-Compliant System	OK	
IRQ 485	Microsoft ACPI-Compliant System	OK	
IRQ 486	Microsoft ACPI-Compliant System	OK	
IRQ 487	Microsoft ACPI-Compliant System	OK	
IRQ 488	Microsoft ACPI-Compliant System	OK	
IRQ 489	Microsoft ACPI-Compliant System	OK	
IRQ 490	Microsoft ACPI-Compliant System	OK	
IRQ 491	Microsoft ACPI-Compliant System	OK	
IRQ 492	Microsoft ACPI-Compliant System	OK	
IRQ 493	Microsoft ACPI-Compliant System	OK	
IRQ 494	Microsoft ACPI-Compliant System	OK	
IRQ 495	Microsoft ACPI-Compliant System	OK	
IRQ 496	Microsoft ACPI-Compliant System	OK	
IRQ 497	Microsoft ACPI-Compliant System	OK	
IRQ 498	Microsoft ACPI-Compliant System	OK	
IRQ 499	Microsoft ACPI-Compliant System	OK	
IRQ 500	Microsoft ACPI-Compliant System	OK	
IRQ 501	Microsoft ACPI-Compliant System	OK	
IRQ 502	Microsoft ACPI-Compliant System	OK	
IRQ 503	Microsoft ACPI-Compliant System	OK	
IRQ 504	Microsoft ACPI-Compliant System	OK	
IRQ 505	Microsoft ACPI-Compliant System	OK	
IRQ 506	Microsoft ACPI-Compliant System	OK	
IRQ 507	Microsoft ACPI-Compliant System	OK	
IRQ 508	Microsoft ACPI-Compliant System	OK	
IRQ 509	Microsoft ACPI-Compliant System	OK	
IRQ 510	Microsoft ACPI-Compliant System	OK	
IRQ 511	Microsoft ACPI-Compliant System	OK	
IRQ 32	Intel(R) Serial IO I2C Host Controller - 54C6	OK	
IRQ 4294967294	PCI Express Root Port #7 - 54BE	OK	
IRQ 4294967288	Intel(R) Management Engine Interface #1	OK	
IRQ 27	Intel(R) Serial IO I2C Host Controller - 54E8	OK	
IRQ 16	Intel(R) Innovation Platform Framework Processor Participant	OK	
IRQ 14	Intel(R) Serial IO GPIO Host Controller - INTC1057	OK	
IRQ 4294967290	Intel(R) GNA Scoring Accelerator module	OK	
IRQ 4294967291	Intel® Smart Sound Technology BUS	OK	
IRQ 4294967292	Intel(R) UHD Graphics	OK	
IRQ 31	Intel(R) Serial IO I2C Host Controller - 54C5	OK	

[Memory]

Resource	Device	Status	
0xFFEF0000-0xFFEFFFFF	Intel(R) Integrated Sensor Solution	OK	
0xFEDC0000-0xFEDC7FFF	Motherboard resources	OK	
0xFEDA0000-0xFEDA0FFF	Motherboard resources	OK	
0xFEDA1000-0xFEDA1FFF	Motherboard resources	OK	
0xC0000000-0xCFFFFFFF	Motherboard resources	OK	
0xFED20000-0xFED7FFFF	Motherboard resources	OK	
0xFED90000-0xFED93FFF	Motherboard resources	OK	
0xFED45000-0xFED8FFFF	Motherboard resources	OK	
0xFEE00000-0xFEEFFFFF	Motherboard resources	OK	
0xFE03E008-0xFE03EFFF	Motherboard resources	OK	
0xFE03F000-0xFE03FFFF	Motherboard resources	OK	
0x115F000-0x115FFFF	Intel Universal Flash Storage (UFS) Host Controller	OK	
0x80400000-0x804FFFFF	Realtek RTL8851BE WiFi 6 802.11ax PCIe Adapter #4	OK	
0x80400000-0x804FFFFF	PCI Express Root Complex	OK	
0x80400000-0x804FFFFF	PCI Express Root Port #7 - 54BE	OK	
0x1120000-0x112FFFF	Intel(R) USB 3.10 eXtensible Host Controller - 1.20 (Microsoft)	OK	
0xFED00000-0xFED003FF	High precision event timer	OK	
0xFFEE9000-0xFFEE9FFF	Intel(R) Serial IO I2C Host Controller - 54E9	OK	
0xA0000-0xBFFFF	PCI Express Root Complex	OK	
0xE8000-0xEBFFF	PCI Express Root Complex	OK	
0xEC000-0xEFFFF	PCI Express Root Complex	OK	
0xFE010000-0xFE010FFF	SPI (flash) Controller - 54A4	OK	
0xFFEE6000-0xFFEE6FFF	Intel(R) Serial IO I2C Host Controller - 54C6	OK	
0xFED40000-0xFED44FFF	Trusted Platform Module 2.0	OK	
0xFFEE8000-0xFFEE8FFF	Intel(R) Management Engine Interface #1	OK	
0x1140000-0x1147FFF	Intel(R) Platform Monitoring Technology Driver	OK	
0xFFEEA000-0xFFEEAFFF	Intel(R) Serial IO I2C Host Controller - 54E8	OK	
0xFFEC0000-0xFFEDFFFF	Intel(R) Innovation Platform Framework Processor Participant	OK	
0xFD6E0000-0xFD6EFFFF	Intel(R) Serial IO GPIO Host Controller - INTC1057	OK	
0xFD6D0000-0xFD6DFFFF	Intel(R) Serial IO GPIO Host Controller - INTC1057	OK	
0xFD6A0000-0xFD6AFFFF	Intel(R) Serial IO GPIO Host Controller - INTC1057	OK	
0xFD690000-0xFD69FFFF	Intel(R) Serial IO GPIO Host Controller - INTC1057	OK	
0xFFEEB000-0xFFEEBFFF	Intel(R) GNA Scoring Accelerator module	OK	
0xFFEEC000-0xFFEEFFFF	Intel® Smart Sound Technology BUS	OK	
0xFFF00000-0xFFFFFFFF	Intel® Smart Sound Technology BUS	OK	
0x0000-0xFFFFFF	Intel(R) UHD Graphics	OK	
0x0000-0xFFFFFFF	Intel(R) UHD Graphics	OK	
0xFFEE7000-0xFFEE7FFF	Intel(R) Serial IO I2C Host Controller - 54C5	OK	

[Components]



[Multimedia]



[Audio Codecs]

CODEC	Manufacturer	Description	Status	File	Version	Size	Creation Date	
c:\windows\system32\l3codeca.acm	Fraunhofer Institut Integrierte Schaltungen IIS	Fraunhofer IIS MPEG Layer-3 Codec	OK	C:\windows\system32\L3CODECA.ACM	1.9.0.401	112.00 KB (114,688 bytes)	5/7/2022 12:20 AM	
c:\windows\system32\msgsm32.acm	Microsoft Corporation		OK	C:\windows\system32\MSGSM32.ACM	10.0.22621.2506	65.96 KB (67,544 bytes)	3/22/2024 10:14 AM	
c:\windows\system32\msadp32.acm	Microsoft Corporation		OK	C:\windows\system32\MSADP32.ACM	10.0.22621.2506	57.89 KB (59,280 bytes)	3/22/2024 10:14 AM	
c:\windows\system32\imaadp32.acm	Microsoft Corporation		OK	C:\windows\system32\IMAADP32.ACM	10.0.22621.2506	61.92 KB (63,408 bytes)	3/22/2024 10:14 AM	
c:\windows\system32\msg711.acm	Microsoft Corporation		OK	C:\windows\system32\MSG711.ACM	10.0.22621.2506	49.80 KB (51,000 bytes)	3/22/2024 10:14 AM	

[Video Codecs]

CODEC	Manufacturer	Description	Status	File	Version	Size	Creation Date	
c:\windows\system32\tsbyuv.dll	Microsoft Corporation		OK	C:\windows\system32\TSBYUV.DLL	10.0.22621.1	40.00 KB (40,960 bytes)	5/7/2022 12:20 AM	
c:\windows\system32\iyuv_32.dll	Microsoft Corporation		OK	C:\windows\system32\IYUV_32.DLL	10.0.22621.1	76.00 KB (77,824 bytes)	5/7/2022 12:20 AM	
c:\windows\system32\msyuv.dll	Microsoft Corporation		OK	C:\windows\system32\MSYUV.DLL	10.0.22621.1	48.00 KB (49,152 bytes)	5/7/2022 12:20 AM	
c:\windows\system32\msrle32.dll	Microsoft Corporation		OK	C:\windows\system32\MSRLE32.DLL	10.0.22621.2506	40.00 KB (40,960 bytes)	3/22/2024 10:15 AM	
c:\windows\system32\msvidc32.dll	Microsoft Corporation		OK	C:\windows\system32\MSVIDC32.DLL	10.0.22621.2506	60.00 KB (61,440 bytes)	3/22/2024 10:15 AM	

[CD-ROM]

Item	Value	

[Sound Device]

Item	Value	
Name	Intel® Smart Sound Technology for Bluetooth® Audio	
Manufacturer	Intel(R) Corporation	
Status	OK	
PNP Device ID	INTELAUDIO\CTLR_DEV_54C8&LINKTYPE_03&DEVTYPE_00&VEN_8086&DEV_AE30&SUBSYS_8B36103C&REV_0001\5&185E6F77&0&0000DIF_000A&UIF_0000	
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\INTCBTAU.INF_AMD64_3F33A33CD49C2173\INTCBTAU.SYS (10.29.0.11516, 893.45 KB (914,896 bytes), 2/5/2025 1:14 AM)	
		
Name	Realtek High Definition Audio	
Manufacturer	Realtek	
Status	OK	
PNP Device ID	INTELAUDIO\FUNC_01&VEN_10EC&DEV_0236&SUBSYS_103C8B36&REV_1000\5&185E6F77&0&0001DIF_000A&UIF_0000	
Driver	C:\WINDOWS\SYSTEM32\DRIVERS\RTKVHD64.SYS (6.0.9752.1, 6.35 MB (6,662,080 bytes), 2/5/2025 1:18 AM)	
		
Name	Intel® Smart Sound Technology for USB Audio	
Manufacturer	Intel(R) Corporation	
Status	OK	
PNP Device ID	INTELAUDIO\CTLR_DEV_54C8&LINKTYPE_06&DEVTYPE_06&VEN_8086&DEV_AE50&SUBSYS_8B36103C&REV_0001\0603DIF_000A&UIF_0000	
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\INTCUSB.INF_AMD64_C0CD7E49204848B2\INTCUSB.SYS (10.29.0.11516, 916.96 KB (938,968 bytes), 2/5/2025 1:14 AM)	
		
Name	Steam Streaming Microphone	
Manufacturer	Valve Corporation Audio DDK	
Status	OK	
PNP Device ID	ROOT\STEAMSTREAMINGMICROPHONE\0000	
Driver	C:\WINDOWS\SYSTEM32\DRIVERS\STEAMSTREAMINGMICROPHONE.SYS (, 39.78 KB (40,736 bytes), 2/4/2025 8:46 PM)	
		
Name	Intel® Smart Sound Technology for Digital Microphones	
Manufacturer	Intel(R) Corporation	
Status	OK	
PNP Device ID	INTELAUDIO\CTLR_DEV_54C8&LINKTYPE_02&DEVTYPE_00&VEN_8086&DEV_AE20&SUBSYS_8B36103C&REV_10EC\5&185E6F77&0&0000DIF_000A&UIF_0000	
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\INTCDMIC.INF_AMD64_A616E4ACFCC1EB12\INTCDMIC.SYS (10.29.0.11516, 766.96 KB (785,368 bytes), 2/5/2025 1:14 AM)	
		
Name	Steam Streaming Speakers	
Manufacturer	Valve Corporation Audio DDK	
Status	OK	
PNP Device ID	ROOT\STEAMSTREAMINGSPEAKERS\0000	
Driver	C:\WINDOWS\SYSTEM32\DRIVERS\STEAMSTREAMINGSPEAKERS.SYS (, 39.78 KB (40,736 bytes), 2/4/2025 8:46 PM)	
		
Name	VB-Audio Virtual Cable	
Manufacturer	VB-Audio Software	
Status	OK	
PNP Device ID	ROOT\MEDIA\0000	
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\VBMMECABLE64_WIN10.INF_AMD64_DD707570A4BF06FD\VBAUDIO_CABLE64_WIN10.SYS (10.0.10011.16384, 137.46 KB (140,760 bytes), 10/8/2024 7:09 AM)	
		
Name	VB-Audio Voicemeeter VAIO	
Manufacturer	VB-Audio Software	
Status	OK	
PNP Device ID	ROOT\MEDIA\0001	
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\VBVOICEMEETERVAIO64_WIN10.INF_AMD64_CE452124B45DD943\VBVOICEMEETERVAIO64_WIN10.SYS (3.3.1.9, 288.95 KB (295,880 bytes), 2/4/2025 10:47 PM)	
		
Name	Oculus Virtual Audio Device	
Manufacturer	Oculus	
Status	OK	
PNP Device ID	ROOT\MEDIA\0002	
Driver	C:\WINDOWS\SYSTEM32\DRIVERS\OCULUSVAD.SYS (10.0.10011.16384, 71.68 KB (73,400 bytes), 3/24/2025 1:29 AM)	

[Display]

Item	Value	
Name	Meta Virtual Monitor	
PNP Device ID	ROOT\DISPLAY\0000	
Adapter Type	Not Available, Meta Inc. compatible	
Adapter Description	Meta Virtual Monitor	
Adapter RAM	Not Available	
Installed Drivers	Not Available	
Driver Version	17.12.55.198	
INF File	oem52.inf (VirtualScreen_Install.NT section)	
Color Planes	Not Available	
Color Table Entries	Not Available	
Resolution	Not Available	
Bits/Pixel	Not Available	
Driver	C:\WINDOWS\SYSTEM32\DRIVERS\WUDFRD.SYS (10.0.22621.4391, 344.00 KB (352,256 bytes), 2/4/2025 8:20 PM)	
		
Name	Intel(R) UHD Graphics	
PNP Device ID	PCI\VEN_8086&DEV_46D0&SUBSYS_8B36103C&REV_00\3&11583659&2&10	
Adapter Type	Intel(R) UHD Graphics Family, Intel Corporation compatible	
Adapter Description	Intel(R) UHD Graphics	
Adapter RAM	1.83 GB (1,967,122,432 bytes)	
Installed Drivers	<>,C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_64dc54263337697d\igd10iumd64.dll,C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_64dc54263337697d\igd10iumd64.dll,C:\windows\System32\DriverStore\FileRepository\iigd_dch.inf_amd64_64dc54263337697d\igd12umd64.dll	
Driver Version	32.0.101.5542	
INF File	oem351.inf (iADLND_w10_DS section)	
Color Planes	Not Available	
Color Table Entries	4294967296	
Resolution	1366 x 768 x 60 hertz	
Bits/Pixel	32	
Memory Address	0x0000-0xFFFFFF	
Memory Address	0x0000-0xFFFFFFF	
I/O Port	0x00004000-0x0000403F	
IRQ Channel	IRQ 4294967292	
Driver	C:\WINDOWS\SYSTEM32\DRIVERSTORE\FILEREPOSITORY\IIGD_DCH.INF_AMD64_64DC54263337697D\IGDKMDN64.SYS (32.0.101.5542, 50.44 MB (52,889,680 bytes), 2/5/2025 1:15 AM)	

[Infrared]

Item	Value	

[Input]



[Keyboard]

Item	Value	
Description	Standard PS/2 Keyboard	
Name	Enhanced (101- or 102-key)	
Layout	00000409	
PNP Device ID	ACPI\HPQ8001\4&8A80C37&0	
Number of Function Keys	12	
I/O Port	0x00000060-0x00000060	
I/O Port	0x00000064-0x00000064	
IRQ Channel	IRQ 1	
Driver	C:\WINDOWS\SYSTEM32\DRIVERS\I8042PRT.SYS (10.0.22621.4391, 156.00 KB (159,744 bytes), 2/4/2025 8:20 PM)	
		
Description	HID Keyboard Device	
Name	Enhanced (101- or 102-key)	
Layout	00000409	
PNP Device ID	HID\CONVERTEDDEVICE&COL01\5&2AED2547&0&0000	
Number of Function Keys	12	
Driver	C:\WINDOWS\SYSTEM32\DRIVERS\KBDHID.SYS (10.0.22621.4391, 72.00 KB (73,728 bytes), 2/4/2025 8:20 PM)	

[Pointing Device]

Item	Value	
Hardware Type	ELAN Input Device	
Number of Buttons	0	
Status	OK	
PNP Device ID	HID\ELAN07BA&COL01\5&1B180818&0&0000	
Power Management Supported	No	
Double Click Threshold	Not Available	
Handedness	Not Available	
Driver	C:\WINDOWS\SYSTEM32\DRIVERS\MOUHID.SYS (10.0.22621.1, 68.00 KB (69,632 bytes), 5/7/2022 12:19 AM)	

[Modem]

Item	Value	
Name	SAMSUNG Mobile USB Modem	
Description	SAMSUNG Mobile USB Modem	
Device ID	USB\VID_04E8&PID_6860&MODEM\6&1E7E88BE&0&0001	
Device Type	External Modem	
Attached To	COM3	
Answer Mode	Not Available	
PNP Device ID	USB\VID_04E8&PID_6860&MODEM\6&1E7E88BE&0&0001	
Provider Name	SAMSUNG Electronics Co., Ltd.	
Modem INF Path	oem32.inf	
Modem INF Section	ssud.Install	
Blind Off	Not Available	
Blind On	Not Available	
Compression Off	Not Available	
Compression On	Not Available	
Error Control Forced	Not Available	
Error Control Off	Not Available	
Error Control On	Not Available	
Flow Control Hard	Not Available	
Flow Control Off	Not Available	
Flow Control Soft	Not Available	
DCB	&#x001c;	
Default		
Inactivity Timeout	0	
Modulation Bell	Not Available	
Modulation CCITT	Not Available	
Prefix	AT	
Pulse	P	
Reset	AT&F<cr>	
Responses Key Name	SAMSUNG Mobile USB Modem::SAMSUNG Electronics Co., Ltd. ::SAMSUNG Electronics Co., Ltd.	
Speaker Mode Dial	Not Available	
Speaker Mode Off	Not Available	
Speaker Mode On	Not Available	
Speaker Mode Setup	Not Available	
Speaker Volume High	Not Available	
Speaker Volume Low	Not Available	
Speaker Volume Med	Not Available	
String Format	Not Available	
Terminator	<cr>	
Tone	T	
Driver	C:\WINDOWS\SYSTEM32\DRIVERS\MODEM.SYS (10.0.22621.2506, 80.00 KB (81,920 bytes), 3/22/2024 10:15 AM)	
```

**Comment by LemonNekoGH** [comment]
Thank you for feedback! I will try to fix the settings after #152 

I'm so sorry we still don't have a tutorial yet...But, you can press `Ctrl + M` to enable move mode, press `Ctrl + R` to enable resize mode, right-click the system tray to close whole application.

**Comment by LemonNekoGH** [comment]
You can press `Ctrl + M` to enable move mode, press `Ctrl + R` to enable resize mode.

You can right-click the system tray to close whole application.

**Comment by LemonNekoGH** [comment]
Sorry we still don't have a tutorial yet...

**Comment by LemonNekoGH** [comment]
Sorry, after my testing, I found the `Ctrl + R` won't enable resize mode, it just refresh the page, and right-click to quit also doesn't work.

**Comment by LemonNekoGH** [comment]
https://github.com/moeru-ai/airi/releases/tag/v0.4.27

Fixed, please try it.

**Comment by HoshinoLunaDev** [comment]
> https://github.com/moeru-ai/airi/releases/tag/v0.4.27
> 
> Fixed, please try it.

I gave it a go and updated to the latest version! It's fixed and works as it should be! Thanks for fixing the bug according to #154 and #156!
